<?php
// $Id$

define('IMAGE_UNMACHINED', 'image_raw');
define('IMAGE_HALFPROCESSED', 'image_halfwork');
define('IMAGE_PROCESSED', 'image_processed');

// mark images (using body field) whose captions aren't edited yet
define('IMAGE_NOT_COMPLETED', '<!--image_not_completed-->');

/**
 * Implementation of hook_menu().
 */
function image_fupload_menu() {
  $items['node/add/%image_node_type/list_images'] = array(
    'title' => 'Edit Captions',
    'access arguments' => array('create images'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fupload_list_images', 2),    
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
* Menu callback; loads a image node type object
*/
function image_node_type_load($node_type) {
  $image_node_types = variable_get('image_node_types', array());
  if (isset($image_node_types[$node_type])) {
    return $node_type;
  } else {
    return FALSE;
  }
}

/**
 * Implementation of hook_help
 */
function image_fupload_help($path, $arg) {
  switch ($path) {
      case 'admin/help#image_fupload':
      $output = '<p>'. t("The Image FUpload module is used to provide an alternate upload form to image module itself.") .'</p>';
      $output .= '<p>'. t("This is a great advantage because multiple images can be selected with one click which are automatically uploaded and processed without any further user interaction. Additionally, this module fully integrates in image module. Consequently, all settings made by image module are observed (thumb creation, file size limit etc.).") .'</p>';
      $output .= '<p>' .t("Image FUpload administration allows to define some characters which are replaced in the node title by a whitespace. In addition to that, the option can be selected to show a link to the original upload form to those users whose browser doesn't support this Flash / JS solution.") . '</p>';
      $output .= t('<p>You can</p>
<ul>
<li>create images using F(lash)Upload at <a href="!node-create-image">node &gt;&gt; create &gt;&gt; image</a>.</li>
<li>configure Image FUpload settings at <a href="!admin-settings-image-fupload">administer &gt;&gt; settings &gt;&gt; image &gt;&gt; image_fupload</a>.</li>
', array('!node-create-image' => url('node/add/image'), '!admin-image-galleries' => url('admin/image/galleries'), '!admin-settings-image-fupload' => url('admin/settings/image/image_fupload'))) .'</ul>';
      $output .= '<p>'. t('For more information please read the configuration and customization handbook <a href="!image">Image FUpload page</a>.', array('!image' => 'http://www.drupal.org/handbook/modules/image/')) .'</p>';
      return $output;
  }
}

/**
 * Implementation of hook_theme() registry.
 **/
function image_fupload_theme() {
  return array(
    'swfupload_settings' => array(
      'template' => 'swfupload-settings',
      'arguments' => array('modulepath' => NULL, 'uploadpath' => NULL, 'maxfilesize' => NULL, 'sessionid' => NULL, 'uploadlimit' => NULL, 'second_step_url' => NULL),      
    ),
    'fupload_create_filename' => array(
      'arguments' => array('image' => NULL,),
    ),
    'fupload_imagepreview_img' => array(
      'arguments' => array('image' => NULL, 'image_info' => NULL, 'node_image' => NULL),
    ),
  );
}

function fupload_filetransfer() {
  // huh.. swfUpload sends some data...let's see
  global $user;
  $sid = $_POST['PHPSESSID'];
  
  // validate given session id
  $result = db_query("SELECT * FROM {sessions} WHERE sid = '%s' AND hostname = '%s' LIMIT 0 , 1", $sid, ip_address());
  $upload_user = db_fetch_object($result);
  if (!empty($upload_user)) {    
    // Get users profile
    $user = user_load(array('uid' => $upload_user->uid));
    
    // Adapt to drupal files structure
    $_FILES['files']['name']['image'] = $_FILES['Filedata']['name'];
    $_FILES['files']['type']['image'] = $_FILES['Filedata']['type'];
    $_FILES['files']['tmp_name']['image'] = $_FILES['Filedata']['tmp_name'];
    $_FILES['files']['error']['image'] = $_FILES['Filedata']['error'];
    $_FILES['files']['size']['image'] = $_FILES['Filedata']['size'];
    
    // Validators for file_save_upload().
    $validators = array(
      'file_validate_is_image' => array(),
      'file_validate_size' => array(variable_get('image_max_upload_size', 800) * 1024),
    );
    if ($file = file_save_upload('image', $validators)) {
      $image = image_get_info($file->filepath); // Get real mime-type
      if(!db_query("UPDATE {files} SET filename = '%s', filemime = '%s' WHERE fid = %d LIMIT 1", IMAGE_UNMACHINED, $image['mime_type'], $file->fid))
        drupal_set_header('HTTP/1.1 405 Upload Error');      
      print 'READY'; // Reply something to satisfy swfUpload
    } else {
      drupal_set_header('HTTP/1.1 408 Image Error');
    }    
    
  } else {
    drupal_access_denied();
  }
}

function fupload_empty_queue() {
  global $user;
  
  // Set "processed" flag so that these images aren't processed again; images are deleted later by cron (--> temporary files)
  db_query("UPDATE {files} SET filename = '%s' WHERE uid = %d AND status = %d AND filename = '%s' LIMIT 100", IMAGE_PROCESSED, $user->uid, FILE_STATUS_TEMPORARY, IMAGE_UNMACHINED);
  
  // Output message to user via AJAX
  drupal_set_message(t('All queued images were deleted.'), 'warning');
  drupal_json(array('status' => TRUE, 'data' => theme('status_messages')));
}

function fupload_list_images(&$form_state, $node_type) {
  global $user;
  $count = 0;
  
  $form['text'] = array('#value' => 'einiger Text, der hier stehen soll.');
  
  $result = db_query("SELECT nid, title FROM {node} WHERE type = '%s' AND status = '0' AND created > %d", $node_type, time() - 86400); // only entries which are one day or newer
  while ($node = db_fetch_object($result)) {
    $count += 1;
    // Get all node infos, also image paths
    $node_image = node_load($node->nid);
    
    // only use this image node if it was produced by image_fupload
    if ($node_image->body == IMAGE_NOT_COMPLETED) {
      $image_nodes[] = $node_image->nid;
    
      $form[$node_image->nid] = array(
        '#type' => 'fieldset',
        '#title' => t('Image @count', array('@count' => $count)),
        '#collapsible' => FALSE,
        '#collapsed' => FALSE,
      );
      $form[$node_image->nid]['preview_image'] = array(
        '#prefix' => '<div class="image_fupload_preview">',
        '#value' => _fupload_imagepreview($node_image, $node_type),
        '#post' => '</div>',
        '#weight' => 1,        
      );      
      $form[$node_image->nid]['title_' .$node_image->nid] = array(
        '#type' => 'textfield',
        '#title' => t('Image title'),
        '#default_value' => isset($form_state['values']['title_' .$node_image->nid]) ? $form_state['values']['title_' .$node_image->nid] : $node_image->title,
        '#size' => 60,
        '#required' => TRUE,
        '#weight' => 3,
      );
      $form[$node_image->nid]['body_' .$node_image->nid] = array(
        '#type' => 'textarea',
        '#title' => t('Body'),
        '#default_value' => isset($form_state['values']['body_' .$node_image->nid]) ? $form_state['values']['body_' .$node_image->nid] : '',
        '#rows' => 5, 
        '#weight' => 5,
      );
      $form[$node_image->nid]['format_' .$node_image->nid] = filter_form($node_image->format, NULL, array('format_' .$node_image->nid));
      $form[$node_image->nid]['format_' .$node_image->nid]['#weight'] = 6;
    }
  }
  
  if (!empty($image_nodes)) {
    $form['#redirect'] = 'node/add/' .$node_type; // redirect to first upload page again
    $form['image_nodes'] = array('#type' => 'value', '#value' => implode(';', $image_nodes));
    $form['submit'] = array('#type' => 'submit', '#value' => t('Done Editing'));
  }
  
  // variable_set('image_node_types', array('image' => array('title' => 'Image', 'fieldname' => 'images', 'image_selection' => 'fupload_preview', 'imagecache_preset' => 'fupload_preview', 'image_dimension' => '127x200')));  
  return $form;
}

function fupload_list_images_submit($form, &$form_state) {
  // get nids of images and start batch process
  $image_nids = explode(';', $form_state['values']['image_nodes']);  
  for ($i = 0; $i < count($image_nids); $i++) { 
    // load full node object  
    $node = node_load($image_nids[$i]);    
    // new changes to node object
    $node->status = 1; // publish node
    $node->title = check_plain($form_state['values']['title_' .$image_nids[$i]]);
    $node->teaser = node_teaser($form_state['values']['body_' .$image_nids[$i]], $form_state['values']['format_' .$image_nids[$i]]);
    $node->body = $form_state['values']['body_' .$image_nids[$i]];
    $node->format = $form_state['values']['format_' .$image_nids[$i]];    
    // save new node object
    node_save($node);
  }
  drupal_set_message(t('All images have been saved and published.'));
  drupal_set_message(t('Additonal images can be selected and uploaded now.'));
  drupal_redirect_form($form);  
}

function theme_fupload_create_filename($image) {
  // Get filename out of filepath
  $filename = trim(basename($image->filepath), ' ');
  $length1 = strlen(strrchr($filename, '.'));
  $length2 = strlen($filename);
  $image_name = ucfirst(substr($filename, 0, ($length2 - $length1)));
        
  // Remove some given (userdefined) elements
  $replacements = explode(';', variable_get('fupload_title_replacements', '_;{;}'));        
  $image_name = str_replace($replacements, ' ', $image_name);
  
  return $image_name;
}

function _fupload_imagepreview($node_image, $node_type) {
  $image_node_types = variable_get('image_node_types', array());
  switch ($node_type) { // need to split image module and other cck related imagemodules to be able to provide the right preview handling
    case 'image':
    
      if (!empty($image_node_types['image']['imagecache_preset'])) {
        // using ImageCache
        $content = theme('imagecache', $image_node_types['image']['imagecache_preset'], $node_image->images['_original'], $node_image->title, $node_image->title);
      } else {
        // using a ready-to-use Image size of Image module
        $image = $node_image->images[$image_node_types['image']['image_selection']];
        $content = theme('fupload_imagepreview_img', $image, image_get_info($image), $node_image);
      }
      break;
    
    default:
      $content = "blablablqqqqqqqqqqe";
      break;
  }
  // $content = '<img src="" width="" height="" title="" alt="" class="image_fupload_preview_image" />';
  
  return $content;
}

function theme_fupload_imagepreview_img($image, $image_info, $node_image) {
  $content = '<img src="' .base_path() . file_create_path($image). '" width="' .$image_info['width']. '" height="' .$image_info['height']. '" title="' .$node_image->title. '" alt="' .$node_image->title. '" class="image_fupload_preview_image" />';
  return $content;
}